### ISSUE TITLE
Error: Cannot find module 'ms' after latest release

### ISSUE THREAD

**Issue by EnzoMartin** [expressjs/serve-favicon#10]
```
Error: Cannot find module 'ms'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\Repos\Project\node_modules\serve-favicon\index.js:16:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Just got this after updating to the newest release (2.1.0)

**Comment by BasiliskEngine** [comment]
Yep, latest version of Express has several lost dependencies. Please fix.

**Comment by dougwilson** [comment]
Hi @BasiliskEngine , this issue is from 2014 and unless you're time traveling, unlikely relates to whatever your are experiencing :) If you have not done so already, please run the following commands to fix any potentional corrupted in your npm cache:
```
$ rm -rf node_modules
$ npm cache clean
$ npm install
```
If that still does not work, please ensure your npm registry is not set to a mirror, but to the official registry:
```
$ npm config set registry https://registry.npmjs.org/ --global
$ npm install
```

And if that fails as well, please open a new issue with a full, complete description of what the error your are experiencing, complete with error logs, etc. :)
```
